# Generated by Django 6.0.3 on 2026-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrafeatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_descriptiion',
            field=models.TextField(max_length=1000),
        ),
    ]
