# Generated by Django 6.0.3 on 2026-03-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrafeatures', '0002_alter_about_options_alter_about_about_descriptiion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociallink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('link', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Follow us',
            },
        ),
    ]
