# Generated by Django 6.0.3 on 2026-03-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrafeatures', '0003_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={},
        ),
    ]
